import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { 
  FileSpreadsheet,
  Loader2, 
  AlertCircle,
  Calendar,
  FileText,
  BarChart3
} from 'lucide-react';
import { reportService } from '@/api/reports';
import { DashboardWidget } from '@/components/DashboardWidget';
import { Button } from '@/components/ui/button';

export const SharedReport = () => {
  const { shareToken } = useParams<{ shareToken: string }>();
  const [report, setReport] = useState<any>(null);
  const [data, setData] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (shareToken) {
      fetchPublicReport(shareToken);
    }
  }, [shareToken]);

  const fetchPublicReport = async (token: string) => {
    try {
      setIsLoading(true);
      const reportData = await reportService.getPublic(token);
      setReport(reportData);
      setData(reportData.data);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setIsLoading(false);
    }
  };

  if (isLoading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-screen text-muted-foreground bg-background">
        <Loader2 className="w-10 h-10 animate-spin mb-4 text-primary" />
        <p className="text-lg font-medium animate-pulse">Loading shared dashboard...</p>
      </div>
    );
  }

  if (error || !report) {
    return (
      <div className="flex flex-col items-center justify-center min-h-screen text-center px-4 bg-background">
        <div className="w-20 h-20 rounded-full bg-destructive/10 flex items-center justify-center mb-6">
          <AlertCircle className="w-10 h-10 text-destructive" />
        </div>
        <h2 className="text-3xl font-bold mb-4">Report Not Found</h2>
        <p className="text-muted-foreground max-w-md mb-8">
          The dashboard you are looking for might have been deleted or the link is incorrect.
        </p>
        <Button size="lg" asChild>
          <Link to="/">Create Your Own Report</Link>
        </Button>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-muted/30 pb-20">
      <header className="h-20 border-b bg-background/95 backdrop-blur sticky top-0 z-10 px-6 flex items-center justify-between shadow-sm">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-lg bg-primary flex items-center justify-center">
            <FileSpreadsheet className="w-6 h-6 text-primary-foreground" />
          </div>
          <div>
            <h1 className="font-bold text-xl tracking-tight leading-tight">{report.title}</h1>
            <p className="text-xs text-muted-foreground">Shared via Sheet Reporting</p>
          </div>
        </div>
        <Button variant="outline" size="sm" asChild className="hidden sm:flex">
          <Link to="/auth/register">Sign Up Free</Link>
        </Button>
      </header>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-10">
        <div className="bg-background border rounded-2xl p-8 shadow-sm">
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
            <div className="space-y-2">
              <h2 className="text-2xl font-bold">{report.title}</h2>
              <div className="flex flex-wrap items-center gap-x-6 gap-y-2 text-sm text-muted-foreground">
                <div className="flex items-center gap-2">
                  <FileText className="w-4 h-4" />
                  <span>{report.sheet.originalName}</span>
                </div>
                <div className="flex items-center gap-2">
                  <Calendar className="w-4 h-4" />
                  <span>{new Date(report.createdAt).toLocaleDateString()}</span>
                </div>
              </div>
            </div>
            {report.description && (
              <p className="text-muted-foreground max-w-xl border-l-4 border-primary/20 pl-4 py-1 italic">
                {report.description}
              </p>
            )}
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          {report.widgets.map((widget: any) => (
            <DashboardWidget key={widget.id} widget={widget} data={data} />
          ))}
        </div>

        <footer className="text-center pt-10 border-t">
          <p className="text-sm text-muted-foreground">
            This dashboard was automatically generated by <span className="font-semibold text-primary">Sheet Reporting AI</span>.
          </p>
          <Button variant="link" asChild className="mt-2">
            <Link to="/">Create your own dashboard for free &rarr;</Link>
          </Button>
        </footer>
      </main>
    </div>
  );
};
